### PR TITLE
#167918849 - Setup Babel7 for Backend

### PR DESCRIPTION
**Pull request by debelistic**
### What does this PR do?

- Setup babel7 and compile from ES6
- Setup bin and dist folder for babel output

### Description of Task to be completed?

- Install babel7 and its dependencies
- Add babel configuration for compiling code
- Add run time generator
- Add ```babel-watch``` for development environment

### How should this be manually tested?

- Run ```npm run build```
- Run ```npm start```

### Any background context you want to provide?

- We compile code from ES6 to previous JavaScript version using Babel7 and its dependencies
- We create bin files called ```dev``` and ```production``` where we required babel and our ```index.js``` file for compiling
- We output them into a new folder called ```dist```
- There won't be need to use ```core-js``` and ```runtime-generator``` modules

### What are the relevant pivotal tracker stories?

-  #167918849

### Implementation Plan

- https://docs.google.com/document/d/10yecLuu6CJm6MxKxkuo-76thPIVBUD3aQfS_iOHTlxo/edit?usp=sharing

### CODE REVIEW

**Comment by victor-nach** [comment]
I think you should add the dist folder to your .gitignore file, so it's not part of what's pushed to github.

**Comment by voke1** [comment]
@debelistic It is necessary we always add `dist` or `build` folder to `.gitignore` so it doesn't get pushed to GitHub for the sake of efficiency, just as @victor-nach suggested.

**Comment by debelistic** [comment]
Thanks @voke1 and @victor-nach. I will make that improvement and re commit right away. Kindly review the `package.json` scripts as well.

**Comment by okobaba1** [comment]
The dist files are in es5, so we are meant to push code written in es6.
I personally feel you should gitignore the dist file

**Comment by debelistic** [comment]
> I think you should add the dist folder to your .gitignore file, so it's not part of what's pushed to github.

Done

**Comment by debelistic** [comment]
> The dist files are in es5, so we are meant to push code written in es6.
> I personally feel you should gitignore the dist file

I've ignored dist folder

**Pull request closed without merging**
