### PR TITLE
#167918849 - Setup Babel for compiling

### PR DESCRIPTION
**Pull request by debelistic**
### What does this PR do?

- Setup babel7 and compile from ES6
- Setup bin and dist folder for babel output

### Description of Task to be completed?

- Install babel7 and its dependencies
- Add babel configuration for compiling code
- Add run time generator
- Add ```babel-watch``` for development environment

### How should this be manually tested?

- Run ```npm run build```
- Run ```npm start```

### Any background context you want to provide?

- We compile code from ES6 to previous JavaScript version using Babel7 and its dependencies
- We create bin files called ```dev``` and ```production``` where we required babel and our ```index.js``` file for compiling
- We output them into a new folder called ```dist```
- There won't be need to use ```core-js``` and ```runtime-generator``` modules

### What are the relevant pivotal tracker stories?

-  #167918849

### Implementation Plan

- https://docs.google.com/document/d/10yecLuu6CJm6MxKxkuo-76thPIVBUD3aQfS_iOHTlxo/edit?usp=sharing

### Questions:

### CODE REVIEW

**Review by anneKay — COMMENTED** [review]
Resolve the conflicts on this branch

**Comment by debelistic** [comment]
> Resolve the conflicts on this branch

I've resolved them

**Review by misanj — APPROVED** [review]
Looks good to me. I suggest you run the build script in your start script like this `npm run build && node ./src/bin/www` I tried it and it works perfectly

**Comment by voke1** [comment]
Greatjob @debelistic You can also effect @misanj suggestion.

**Review by voke1 — APPROVED** [review]

**Review by anneKay — APPROVED** [review]

**Review by uggoprince — COMMENTED** [review]
@debelistic you are doing a great job. please pay attention to this few changes.
Since we the `www` file, we are not suppose to listen for connections in the `index.js` file.
 Your `www` file content should look like this:
```
require('@babel/register');
require('@babel/core');
const http = require('http');
const app = require('../../src/index.js');

const port = parseInt(process.env.PORT, 10) || 3000;

const server = http.createServer(app);
server.listen(port, function() {
    console.log("Listening on port " + port);
});
```
Then in `index.js` file remove the and put `export default app;`

**Pull request merged**
