### PR TITLE
#167918849 Setup Unit Testing for Backend functionality

### PR DESCRIPTION
**Pull request by debelistic**
### What does this PR do?

- Setup Unit Testing for Backend functionalities
- Test functionanlity

### Description of Task to be completed?

- Install ```mocha``` test runner and chai with ```chai-http``` assertion folder
- Add test runner scripts to ```package.json```
- Add test for index route

### How should this be manually tested?

- Run ```npm test```

### Any background context you want to provide?

- We added a test for index app route to ensure test setup is  working properly

### What are the relevant pivotal tracker stories?

- #167918849

### Implementation Plan

- https://docs.google.com/document/d/1ndZpuEktNDfkzCqFerAzo7vEOpOzCN53uevFf-PuoUc/edit?usp=sharing

### Questions:

### CODE REVIEW

**Review by uggoprince — CHANGES_REQUESTED** [review]
in the test directory you need to create a file and name it prefarably app.js
The content should be like this
```
import 'core-js/stable';
import 'regenerator-runtime/runtime';
import dotenv from 'dotenv';
import app from '../server/index';

dotenv.config();

app.listen(process.env.PORT);

export default app;
```
then every other test file will import the app.js in test directory.

we are not suppose to do app.listen() in index.js because its less efficient. It better to create a `bin` directory inside `src`, and inside of `bin` create a `www` file. It is in this file we listen for connections in the  application.

For tests we have a separate connection which is what I'm showing you above.

`core-js` and `regenerator-runtime` are necessary for the handle async and awaits. Babel no more does that. Install them to `dependencies`.

Secondly in the `indexRoutTest.js` file import chai like so: `import chai, { expect } from 'chai'`;

Thirdly the `dist` folder should be added to `.gitignore`. It's not suppose to be on github. Heroku will handle that from the `build` script in package.json

The script section of package.json should look like this:
```
"clean": "rm -rf dist && mkdir dist",
"build-app": "babel -d ./build/src ./src -s",
"build": "npm run clean && npm run build-app",
"start": "node ./dist/bin/www",
"start:dev": "nodemon --exec babel-node ./src/bin/www",

**Comment by debelistic** [comment]
> in the test directory you need to create a file and name it prefarably app.js
> The content should be like this
> 
> ```
> import 'core-js/stable';
> import 'regenerator-runtime/runtime';
> import dotenv from 'dotenv';
> import app from '../server/index';
> 
> dotenv.config();
> 
> app.listen(process.env.PORT);
> 
> export default app;
> ```
> 
> then every other test file will import the app.js in test directory.
> 
> we are not suppose to do app.listen() in index.js because its less efficient. It better to create a `bin` directory inside `src`, and inside of `bin` create a `www` file. It is in this file we listen for connections in the application.
> 
> For tests we have a separate connection which is what I'm showing you above.
> 
> `core-js` and `regenerator-runtime` are necessary for the handle async and awaits. Babel no more does that. Install them to `dependencies`.
> 
> Secondly in the `indexRoutTest.js` file import chai like so: `import chai, { expect } from 'chai'`;
> 
> Thirdly the `dist` folder should be added to `.gitignore`. It's not suppose to be on github. Heroku will handle that from the `build` script in package.json
> 
> The script section of package.json should look like this:
> 
> ```
> "clean": "rm -rf dist && mkdir dist",
> "build-app": "babel -d ./build/src ./src -s",
> "build": "npm run clean && npm run build-app",
> "start": "node ./dist/bin/www",
> "start:dev": "nodemon --exec babel-node ./src/bin/www",
> ```

I've set up for the bin folder on Babel setup PR once its merged it'll we'll be added. For `async` and `await` run time generators, I think they should be required only in files where they are needed just to properly keep track.

I like the `www` file you used in running the app. For your `devstart` script I don't think there is a need to use `nodemon` especially since it enhances hot reload and your build don't change in development until you run build. You could use the uncompiled file in production, the purpose of babel-node is to help with hot reload while compiling.

Babel has a tool called `babel-watch`, which I feel you should look into. Its way more efficient and faster than `nodemon`. You would have something like:
`babel-watch ./src/index.js`.

Instead of having three scripts to handle build, you could just use one. Something like this:
`"build":"rm -rf dist && mkdir dist && babel src -s -d dist"`. It will remove the `dist` folder, if it exists, if not it will move to the next command

I will improve my babel branch to use `www` file instead of the `dev` and `production` files, I had earlier.

**Comment by uggoprince** [comment]
> > in the test directory you need to create a file and name it prefarably app.js
> > The content should be like this
> > ```
> > import 'core-js/stable';
> > import 'regenerator-runtime/runtime';
> > import dotenv from 'dotenv';
> > import app from '../server/index';
> > 
> > dotenv.config();
> > 
> > app.listen(process.env.PORT);
> > 
> > export default app;
> > ```
> > 
> > 
> > then every other test file will import the app.js in test directory.
> > we are not suppose to do app.listen() in index.js because its less efficient. It better to create a `bin` directory inside `src`, and inside of `bin` create a `www` file. It is in this file we listen for connections in the application.
> > For tests we have a separate connection which is what I'm showing you above.
> > `core-js` and `regenerator-runtime` are necessary for the handle async and awaits. Babel no more does that. Install them to `dependencies`.
> > Secondly in the `indexRoutTest.js` file import chai like so: `import chai, { expect } from 'chai'`;
> > Thirdly the `dist` folder should be added to `.gitignore`. It's not suppose to be on github. Heroku will handle that from the `build` script in package.json
> > The script section of package.json should look like this:
> > ```
> > "clean": "rm -rf dist && mkdir dist",
> > "build-app": "babel -d ./build/src ./src -s",
> > "build": "npm run clean && npm run build-app",
> > "start": "node ./dist/bin/www",
> > "start:dev": "nodemon --exec babel-node ./src/bin/www",
> > ```
> 
> I've set up for the bin folder on Babel setup PR once its merged it'll we'll be added. For `async` and `await` run time generators, I think they should be required only in files where they are needed just to properly keep track.
> 
> I like the `www` file you used in running the app. For your `devstart` script I don't think there is a need to use `nodemon` especially since it enhances hot reload and your build don't change in development until you run build. You could use the uncompiled file in production, the purpose of babel-node is to help with hot reload while compiling.
> 
> Babel has a tool called `babel-watch`, which I feel you should look into. Its way more efficient and faster than `nodemon`. You would have something like:
> `babel-watch ./src/index.js`.
> 
> Instead of having three scripts to handle build, you could just use one. Something like this:
> `"build":"rm -rf dist && mkdir dist && babel src -s -d dist"`. It will remove the `dist` folder, if it exists, if not it will move to the next command
> 
> I will improve my babel branch to use `www` file instead of the `dev` and `production` files, I had earlier.

**Review by uggoprince — CHANGES_REQUESTED** [review]
in the test directory you need to create a file and name it prefarably app.js
The content should be like this
```
import 'core-js/stable';
import 'regenerator-runtime/runtime';
import dotenv from 'dotenv';
import app from '../server/index';

dotenv.config();

app.listen(process.env.PORT);

export default app;
```
then every other test file will import the app.js in test directory.

we are not suppose to do app.listen() in index.js because its less efficient. It better to create a `bin` directory inside `src`, and inside of `bin` create a `www` file. It is in this file we listen for connections in the  application.

For tests we have a separate connection which is what I'm showing you above.

`core-js` and `regenerator-runtime` are necessary for the handle async and awaits. Babel no more does that.

Secondly in the `indexRoutTest.js` file import chai like so: `import chai, { expect } from 'chai'`;

@debelistic I forgot this, `package-lock.json` should be added to `.gitignore`

the your test script on package.json would be like this:
`"set NODE_ENV=test nyc mocha --require @babel/register ./src/test --exit --recursive --timeout"`

install package `nyc` in devDependencies. That is what we'll used for `code coverage`

**Comment by anneKay** [comment]
You have commits for setting up babel in this PR and also have commits for setting up testing in another PR. Can you separate these tasks in the PRs so we can actually know what PR and task that is getting reviewed

**Comment by debelistic** [comment]
> You have commits for setting up babel in this PR and also have commits for setting up testing in another PR. Can you separate these tasks in the PRs so we can actually know what PR and task that is getting reviewed

@anneKay I've reverted the files changes, but I don't know how to remove the commit yet

**Comment by debelistic** [comment]
> in the test directory you need to create a file and name it prefarably app.js
> The content should be like this
> 
> ```
> import 'core-js/stable';
> import 'regenerator-runtime/runtime';
> import dotenv from 'dotenv';
> import app from '../server/index';
> 
> dotenv.config();
> 
> app.listen(process.env.PORT);
> 
> export default app;
> ```
> 
> then every other test file will import the app.js in test directory.
> 
> we are not suppose to do app.listen() in index.js because its less efficient. It better to create a `bin` directory inside `src`, and inside of `bin` create a `www` file. It is in this file we listen for connections in the application.
> 
> For tests we have a separate connection which is what I'm showing you above.
> 
> `core-js` and `regenerator-runtime` are necessary for the handle async and awaits. Babel no more does that.
> 
> Secondly in the `indexRoutTest.js` file import chai like so: `import chai, { expect } from 'chai'`;
> 
> @debelistic I forgot this, `package-lock.json` should be added to `.gitignore`
> 
> the your test script on package.json would be like this:
> `"set NODE_ENV=test nyc mocha --require @babel/register ./src/test --exit --recursive --timeout"`
> 
> install package `nyc` in devDependencies. That is what we'll used for `code coverage`

There won't be a need to use corejs or runtime generator. I setup a babel plugin to take care of that. See the babel PR to note things you mentioned here

**Pull request closed without merging**
